version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - run: 
        command: |
          echo Running test &&
          echo `curl -s -H "Authorization\: token $GITHUB_TOKEN" https://api.github.com/repos/appfolio/apm_bundle/commits/cf312891da27d2a4631007407217d9d197b6a214'`
      - run: export REMOTE_BRANCH=`[[ $CIRCLE_BRANCH =~ ^trigger=(.+)$ ]] && echo ${BASH_REMATCH[1]}` && git clone -b $REMOTE_BRANCH --depth 1 -- git@github.com:praxis/attributor.git
      - run: echo `ls attributor/*`
workflows:
  version: 2
  build_and_test:
    jobs:
      - build