version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: export REMOTE_BRANCH=`[[ $CIRCLE_TAG =~ ^trigger=(.+)$ ]] && echo ${BASH_REMATCH[1]}` && git clone -b $CIRCLE_TAG --depth 1 -- git@github.com:praxis/attributor.git
      - run: echo `ls attributor/*`
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^trigger.*/
            